CREATE NONCLUSTERED INDEX [PersonHermano_IDX_01]
	ON [dbo].[PersonHermano]
	(
		[Id] ASC, 
		[FechaCreado] DESC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
	GO